name: vrchat
description: "VRCN"
publish_to: "none"
version: 1.1.0+77

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # VRChat API
  vrchat_dart: ^3.6.0

  # パス
  path_provider: ^2.0.11

  shared_preferences: ^2.5.3

  # Keychain
  flutter_secure_storage: ^9.2.4

  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  # 環境変数
  flutter_dotenv: ^5.2.1

  # アプリ情報
  package_info_plus: ^8.0.0

  # キャッシュ
  cached_network_image: ^3.4.1
  flutter_cache_manager: ^3.4.1

  # フォント
  google_fonts: ^6.2.1

  # アイコン
  flutter_launcher_icons: ^0.14.3
  flutter_dynamic_icon_plus: ^1.3.1
  # android_dynamic_icon: ^2.0.0

  # Firebase
  firebase_core: ^3.13.0
  firebase_analytics: ^11.5.2
  firebase_crashlytics: ^4.3.9
  firebase_performance: ^0.10.1+9

  # スプラッシュ
  flutter_native_splash: ^2.4.6

  url_launcher: ^6.3.1

  # ローカル通知
  flutter_local_notifications: ^19.1.0

  # 二段階認証
  otp: ^3.1.3

  # 画面遷移
  go_router: ^15.1.1

  # フォーマット
  intl: ^0.20.2

  # 共有
  share_plus: ^11.0.0

  # アニメーション
  flutter_animate: ^4.5.2

  # グリッドレイアウト
  flutter_staggered_grid_view: ^0.7.0
  flutter_staggered_animations: ^1.1.1

  # ローディング
  shimmer: ^3.0.0

  # ファビコン
  favicon: ^1.1.2

  http: ^1.3.0

  # パレットジェネレーター
  palette_generator: ^0.3.3+6
  local_auth: ^2.3.0

  # OSC
  osc: ^1.0.0

  # Deeplink
  app_links: ^6.4.0

  timezone: ^0.10.1

  # バッジ
  flutter_app_badge_control: ^0.0.2

  flutter_background_service: ^5.1.0
  flutter_background_service_android: ^6.3.0
  flutter_background_service_ios: ^5.0.3

  # Shorebird
  shorebird_code_push: ^2.0.4

  device_info_plus: ^11.5.0
  apple_product_name: ^3.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  rexios_lints: ^11.0.4
  build_runner: ^2.4.15
  riverpod_generator: ^2.6.5

flutter:
  uses-material-design: true

  generate: true

  assets:
    - path: assets/icons/
    - path: assets/images/
    - path: .env
      flavors:
        - dev
    - shorebird.yaml

  # fonts:
  #   - family: LINESeedJP
  #     fonts:
  #       - asset: assets/fonts/LINESeedJP/LINESeedJP_A_TTF_Th.ttf
  #         weight: 100
  #       - asset: assets/fonts/LINESeedJP/LINESeedJP_A_TTF_Rg.ttf
  #         weight: 400
  #       - asset: assets/fonts/LINESeedJP/LINESeedJP_A_TTF_Bd.ttf
  #         weight: 700
  #       - asset: assets/fonts/LINESeedJP/LINESeedJP_A_TTF_Eb.ttf
  #         weight: 900

flutter_icons:
  image_path_android: assets/launcher_icon/android_icon.png
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: assets/launcher_icon/android_icon.png
  image_path_ios: assets/launcher_icon/ios_icon.png
  android: true
  adaptive_icon_padding: true
  min_sdk_android: 30
  ios: true

flutter_native_splash:
  color: "#262626"
  image: assets/images/splash.png
  color_dark: "#262626"
  image_dark: assets/images/splash.png
  fullscreen: false
  android_12:
    icon_background_color: "#262626"
    image: assets/images/splash.png
    icon_background_color_dark: "#262626"
    image_dark: assets/images/splash.png
